In [1]:
import numpy as np 

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [2]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [3]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [4]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [5]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)  # Prevent overflow by subtracting the max
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [6]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
np.sum(y)  # This should be 1.0

[0.01821127 0.24519181 0.73659691]


np.float64(1.0)

In [8]:
import math

def softmax(a):
    exp_a = [math.exp(i) for i in a]
    sum_exp_a = sum(exp_a)

    return [i / sum_exp_a for i in exp_a]

x = [0.3, 2.9, 4.0]
result = softmax(x)
print(result)

[0.018211273295547534, 0.2451918129350739, 0.7365969137693785]


In [9]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))  # This will cause overflow


C:\Users\user\AppData\Local\Temp\ipykernel_11572\1243162138.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))  # This will cause overflow
C:\Users\user\AppData\Local\Temp\ipykernel_11572\1243162138.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))  # This will cause overflow


array([nan, nan, nan])

In [10]:
c = np.max(a)
a - c


array([  0, -10, -20])

In [11]:
np.exp(a - c) / np.sum(np.exp(a - c))  # This will not cause overflow

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])