In [1]:
import numpy as np

X = np.array([1, 2])
X.shape

(2,)

In [2]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [3]:
W.shape

(2, 3)

In [4]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
