<a href="https://colab.research.google.com/github/KweonTJ/Deep_Learning/blob/main/Deep_Learning_0908.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning
- 2026년 9월 8일
- 딥러닝, 코랩, 아나콘다, 파이썬 기본 사용 방법 학습

In [3]:
1+2

3

In [4]:
3**2

9

In [6]:
type(10)

int

In [7]:
type(2.718)

float

In [8]:
type("hello")

str

In [9]:
x=10
print(x)

10


In [11]:
for i in [1, 2, 3]:
  print (i)

1
2
3


In [15]:
def hello():
  print("Hello World!")

hello()

Hello World!


In [25]:
import numpy as np
x=np.array([1.0, 2.0, 3.0])
y=np.array([2.0, 4.0, 6.0])


print(x)
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[1. 2. 3.]
[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [26]:
x+y

array([3., 6., 9.])

In [27]:
x-y

array([-1., -2., -3.])

In [28]:
x*y

array([ 2.,  8., 18.])

In [29]:
x/y

array([0.5, 0.5, 0.5])